### PR TITLE
New session: Focus on enterprise-level metrics

### PR DESCRIPTION
**Pull request by yanfosec**
How to generate enterprise-level metrics using openSAMM, making the framework more useful to large enterprises.

### CODE REVIEW

**Comment by yanfosec** [comment]
Perhaps it would be better under openSAMM instead of CISO?

**Comment by DinisCruz** [comment]
great track, 

In terms of location, it might be even better on an 'Metrics' track

**Comment by DinisCruz** [comment]
@yanfosec couple minor comments
 - the file name needs to be .md
 - you don't need to register as a participant if you are an organizer
 - OpenSAMM is now called OwaspSAMM

**Comment by DinisCruz** [comment]
FYI https://github.com/OWASP/owasp-summit-2017/commit/a2d477e1cb2eb48bcfce667bcd6ce3739d90cf77

**Comment by yanfosec** [comment]
Sorry about the mistakes, my first time working with sending website updates through Git...Anything else I can / need to do?Thank you,Yan Kravchenko
          
            
            On May 4 2017, at 3:52 pm, Dinis Cruz <notifications@github.com> wrote:
            
            
              @yanfosec couple minor comments

the file name needs to be .md
you don't need to register as a participant if you are an organizer
OpenSAMM is now called OwaspSAMM

**Comment by DinisCruz** [comment]
no worries, it is great to you have your contributions.

Where it would be great if you could help is in improving the text/content of the Sessions you are now the organizer and to reach-out to possible participants (i.e. invite who would be great to have at those Working Sessions)

**Comment by yanfosec** [comment]
Sure, I will work on that... I am also speaking on a panel organized by insurance providers in a few weeks, I will collect any useful information there to pass along as well.What do you think the chances are that I will be able to find funding?  
          
            
            On May 4 2017, at 4:21 pm, Dinis Cruz <notifications@github.com> wrote:
            
            
              no worries, it is great to you have you contributions.
Where it would be great if you could help is in improving the text/content of the Sessions you are now the organizer and to reach-out to possible participants (i.e. invite who would be great to have at those Working Sessions)

**Comment by DinisCruz** [comment]
hi @ante-gulam check this new thread about metrics

After it was merged it is now here http://owaspsummit.org/Working-Sessions/CISO/SAMM-Metrics-for-Enterprise.html

**Pull request merged**
