### PR TITLE
Create OWASP-Top-10-Call-for-Data-and-Weightings-Discussion.md

### PR DESCRIPTION
**Pull request by gracerpmg**

### CODE REVIEW

**Comment by Ambg05** [comment]
typo line 31 'lso' to correct, & can you add a link to Brian Glas' blog? 
https://guides.github.com/features/mastering-markdown/#examples will help you do it.

**Comment by Ambg05** [comment]
here's what you do to make the blog link prettier :)

See Brian Glas' blog for [Tools Augmented with Humans vs. Humans with Augmented Technology.](https://nvisium.com/blog/2017/04/24/musings-on-the-owasp-top-10-2017-rc1-pt2/)

NO space between square brackets & round.

Do that & i'll check it.

**Comment by Ambg05** [comment]
beautiful!

**Comment by gracerpmg** [comment]
done

**Pull request merged**
