### PR TITLE
REST IAM workshop proposal

### PR DESCRIPTION
**Pull request by JohanPeeters**

### CODE REVIEW

**Comment by DinisCruz** [comment]
Hi @JohanPeeters , this branch has conflicts, can you take a look at it?

**Comment by bkimminich** [comment]
I took care of that and also moved the misplaced sessions file into the right place.

**Comment by JohanPeeters** [comment]
Thanks @bkimminich.
The REST working session does not appear on the web site. Did something go wrong or has the commit simply not been deployed yet?

**Comment by DinisCruz** [comment]
The problem was the title property (which was set to 'Cheatsheets')

I'll fix it now

**Comment by DinisCruz** [comment]
See http://owaspsummit.org/Working-Sessions/REST-IAM.html

image

**Pull request merged**
