### PR TITLE
Update Implications-of-Owasp-Top-10-2017.md

### PR DESCRIPTION
**Pull request by gracerpmg**

### CODE REVIEW

**Comment by Ambg05** [comment]
Can you change the status to 'need outcomes; need working materials' & I think if you're saying 'need working materials' you don't need to say 'need content' aswell, as the content is part of the working materials. What say you?

**Comment by gracerpmg** [comment]
OK - just realised that content is subordinate to working materials.

If it says missing it means it was done before you sent that replace
missing to needs msg.

Thanks,

/rg

**Comment by Ambg05** [comment]
I thought as much, but as these PRs haven't been merged we might as well make the changes now.

**Comment by gracerpmg** [comment]
Done

**Pull request merged**
