### PR TITLE
Changes workshops

### PR DESCRIPTION
**Pull request by jowasp**
Hi Dinis, submitting my workshop content

### CODE REVIEW

**Comment by DinisCruz** [comment]
nice @jowasp

So your workshop at the moment has a feel of a training (which is not a problem at all, btw). Just thinking of the best way to present it and set it up

Have you reached out to the Bytecodevierwer community?

**Comment by jowasp** [comment]
Sure, the project leader Konloch has already seen the code ;-) but the sessions is to improve after the workshop and make a final submission

**Comment by DinisCruz** [comment]
ok cool, that make sense

**Comment by DinisCruz** [comment]
actually that project leader (Konloch) is the kind of talent that would be great if we could attract to the summit

**Pull request merged**
