### PR TITLE
Create Bernhard_Mueller.md

### PR DESCRIPTION
**Pull request by muellerberndt**
Add myself :)

### CODE REVIEW

**Comment by DinisCruz** [comment]
Hi @b-mueller welcome on board

Can you create the pages for the workshops you both want to lead? (or expand existing ones)

Regarding the financial support we should have a first solution for it very soon. Btw, where are you and Sven_Schleier flying from?

Note (also for @bkimminich) for cross pages links (like the ones in this commit) we need to use virtual paths and use .html (since most users will see this page at the owaspsummit.org site, see what I mean at http://owaspsummit.org/Participants/Bernhard-Mueller.html )

**Comment by DinisCruz** [comment]
@b-mueller @bkimminich ok, I just fixed the links and updated the Mobile Security page to make reference that you two are the organizers (and ignore my 'workshops' question above)

See https://github.com/OWASP/owasp-summit-2017/commit/d7d15a1a7632a7f81fa9cfd64769e6523333cdb1

http://localhost:4000/Workshops/Mobile-Security.html

**Comment by muellerberndt** [comment]
Thanks @DinisCruz - FYI Sven and I are flying from Singapore.

**Comment by DinisCruz** [comment]
ok can you add that info (flight location) to your 'participant' metadata?

**Pull request merged**
