### PR TITLE
Create Collaboratively-Write-Revised-and-New-Text

### PR DESCRIPTION
**Pull request by gracerpmg**
Possibly Working Session needs to move to Type, to reduce length of session title

### CODE REVIEW

**Comment by Ambg05** [comment]
Add .md to the end of the file title.

**Comment by gracerpmg** [comment]
done

**Comment by Ambg05** [comment]
delete working session from Working-session-collaboratively-write-revised-and-new-text, don't you think?

**Review by Ambg05 — APPROVED** [review]

**Comment by gracerpmg** [comment]
done

**Pull request merged**
